export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const CHANGE_ITEM_ATTRIBUTES = 'CHANGE_ITEM_ATTRIBUTES';
export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';
export const INCREASE_ITEM_COUNT = 'INCREASE_ITEM_COUNT';
export const DECREASE_ITEM_COUNT = 'DECREASE_ITEM_COUNT';
export const ORDER_ITEMS = 'ORDER_ITEMS';
